package main

import (
	"net/http"
)

func (a *App) registerRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /favicon.svg", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "image/svg+xml")
		w.Header().Set("Cache-Control", "max-age=86400")
		w.Write([]byte(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#58a6ff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/></svg>`))
	})
	mux.HandleFunc("GET /", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/" {
			http.NotFound(w, r)
			return
		}
		http.Redirect(w, r, "/browse", http.StatusFound)
	})
	mux.HandleFunc("GET /browse", a.handleBrowse)
	mux.HandleFunc("GET /recent", a.handleRecent)

	mux.HandleFunc("GET /file", a.handleServeFile)
	mux.HandleFunc("GET /api/photo/exif", a.handlePhotoExif)
	mux.HandleFunc("GET /thumbnail", a.handleThumbnail)
	mux.HandleFunc("GET /hls/playlist", a.handleHLSPlaylist)
	mux.HandleFunc("GET /hls/segment", a.handleHLSSegment)
	mux.HandleFunc("GET /transcode/stream", a.handleTranscodeStream)
	mux.HandleFunc("POST /api/client-log", a.handleClientLog)
	mux.HandleFunc("POST /api/file/rename", a.handleFileRename)
	mux.HandleFunc("POST /api/file/delete", a.handleFileDelete)
	mux.HandleFunc("POST /api/file/move", a.handleFileMove)
	mux.HandleFunc("POST /api/file/upload", a.handleFileUpload)
	mux.HandleFunc("POST /api/file/hash-matches", a.handleFileHashMatches)
	mux.HandleFunc("GET /api/pdf/markdown",          a.handlePDFMarkdown)
	mux.HandleFunc("GET /api/folder/download",      a.handleFolderDownload)
	mux.HandleFunc("POST /api/folder/delete",       a.handleFolderDelete)
	mux.HandleFunc("POST /api/folder/create",       a.handleFolderCreate)
	mux.HandleFunc("POST /api/folder/rename",       a.handleFolderRename)
	mux.HandleFunc("POST /api/folder/move",         a.handleFolderMove)
	mux.HandleFunc("POST /api/folder/playlist-add", a.handleFolderPlaylistAdd)
	mux.HandleFunc("GET /video/position", a.handleGetVideoPosition)
	mux.HandleFunc("POST /video/position", a.handleSaveVideoPosition)
	mux.HandleFunc("GET /api/bookmarks", a.handleListBookmarks)
	mux.HandleFunc("POST /api/bookmarks", a.handleAddBookmark)
	mux.HandleFunc("POST /api/bookmarks/{id}/delete", a.handleDeleteBookmark)
	mux.HandleFunc("GET /play/stats", a.handlePlayStats)
	mux.HandleFunc("GET /settings", a.handleSettingsPage)
	mux.HandleFunc("GET /api/path-size", a.handlePathSize)
	mux.HandleFunc("POST /paths", a.handlePathAdd)
	mux.HandleFunc("POST /paths/{id}/delete", a.handlePathDelete)
	mux.HandleFunc("POST /paths/{id}/toggle", a.handlePathToggle)
	mux.HandleFunc("GET /search", a.handleSearch)
	mux.HandleFunc("GET /search/files", a.handleSearchFiles)
	mux.HandleFunc("GET /search/status", a.handleSearchStatus)
	mux.HandleFunc("POST /search/reindex", a.handleSearchReindex)

	mux.HandleFunc("GET /stats",             a.handleStatsPage)
	mux.HandleFunc("GET /folder/play",       a.handleFolderPlay)
	mux.HandleFunc("GET /favorites",           a.handleFavoritesPage)
	mux.HandleFunc("GET /favorites/list",      a.handleFavoriteList)
	mux.HandleFunc("POST /favorites/toggle",   a.handleFavoriteToggle)
	mux.HandleFunc("POST /favorites/reorder",  a.handleFavoriteReorder)
	mux.HandleFunc("GET /playlists", a.handlePlaylistList)
	mux.HandleFunc("POST /playlists", a.handlePlaylistCreate)
	mux.HandleFunc("GET /playlists/{id}", a.handlePlaylistDetail)
	mux.HandleFunc("POST /playlists/{id}/delete", a.handlePlaylistDelete)
	mux.HandleFunc("POST /playlists/{id}/items", a.handlePlaylistItemAdd)
	mux.HandleFunc("POST /playlists/{id}/reorder", a.handlePlaylistReorder)
	mux.HandleFunc("POST /playlists/{id}/items/{item_id}/delete", a.handlePlaylistItemDelete)
	mux.HandleFunc("GET /playlists/{id}/state", a.handleGetPlaylistState)
	mux.HandleFunc("POST /playlists/{id}/state", a.handleSavePlaylistState)
	mux.HandleFunc("GET /users", a.handleUserList)
	mux.HandleFunc("GET /users/{id}", a.handleUserDetail)
	mux.HandleFunc("POST /users", a.handleUserCreate)
	mux.HandleFunc("POST /users/{id}/delete", a.handleUserDelete)
	mux.HandleFunc("POST /paths/{id}/grant", a.handlePathGrant)
	mux.HandleFunc("POST /paths/{id}/revoke/{uid}", a.handlePathRevoke)
	mux.HandleFunc("GET /trash", a.handleTrashPage)
	mux.HandleFunc("POST /trash/empty", a.handleTrashEmpty)
	mux.HandleFunc("POST /trash/{id}/restore", a.handleTrashRestore)
	mux.HandleFunc("POST /trash/{id}/purge", a.handleTrashPurge)
	mux.HandleFunc("GET /duplicates", a.handleDuplicatesPage)
	mux.HandleFunc("POST /duplicates/scan", a.handleDuplicatesScan)
	mux.HandleFunc("GET /duplicates/status", a.handleDuplicatesStatus)
}
