#!/usr/bin/env bash
# Regenerates static/vendor.js (three.js + OrbitControls + STLLoader + three-mesh-bvh, one
# minified ESM file). Run by hand when bumping a version; the output is committed so the
# Nix build needs no network.
set -euo pipefail
THREE=0.186.1
BVH=0.9.15
cd "$(dirname "$0")"
W=$(mktemp -d); trap 'rm -rf "$W"' EXIT
mkdir -p "$W/node_modules/three" "$W/node_modules/three-mesh-bvh"
curl -sfL "https://registry.npmjs.org/three/-/three-$THREE.tgz" | tar xz -C "$W/node_modules/three" --strip-components=1
curl -sfL "https://registry.npmjs.org/three-mesh-bvh/-/three-mesh-bvh-$BVH.tgz" | tar xz -C "$W/node_modules/three-mesh-bvh" --strip-components=1
cp entry.js "$W/"
(cd "$W" && nix run nixpkgs#esbuild -- entry.js --bundle --format=esm --minify --outfile=vendor.js)
{ echo "/* three@$THREE three-mesh-bvh@$BVH — generated by jsbundle/build.sh, do not edit */"; cat "$W/vendor.js"; } > ../static/vendor.js
echo "wrote static/vendor.js"
